-- comando
-- psql.exe -d db_sata -U postgres -f "F:\Lynton\eclipse-workspace\sata\scripts\banco\scriptCargaAtivo.sql"

COPY "Ativo" ("codigoAtivo", "nomeEmpresa") FROM stdin;
ABCB4	ABC BRASIL PN
BBAS3	BRASIL ON
BBDC4	BRADESCO PN
BRFS3	BRF FOODS ON
BVMF3	BMFBOVESPA ON
CCRO3	CCR SA ON
CIEL3	CIELO ON
CMIG4	CEMIG PN
CRUZ3	SOUZA CRUZ ON
CSNA3	SID NACIONAL ON
CYRE3	CYRELA REALT ON
ELET3	ELETROBRAS ON
EMBR3	EMBRAER ON
FIBR3	FIBRIA ON
GFSA3	GAFISA ON
GGBR4	GERDAU PN
GOLL4	GOL PN
HYPE3	HYPERMARCAS ON
ITSA4	ITAUSA PN
ITUB4	ITAUUNIBANCO PN
JBSS3	JBS ON
LAME4	LOJAS AMERIC PN
LREN3	LOJAS RENNER ON
MMXM3	MMX MINER ON
MRVE3	MRV ON
NATU3	NATURA ON
OGXP3	OGX PETROLEO ON
PCAR4	P.ACUCAR-CBD PN
PDGR3	PDG REALT ON
PETR4	PETROBRAS PN
RDCD3	REDECARD ON
RSID3	ROSSI RESID ON
TAMM4	TAM S/A PN
TCSL4	TIM PART S/A PN
TNLP4	TELEMAR PN
USIM5	USIMINAS PNA
VALE5	VALE PNA
VIVO4	VIVO PN
\.
